FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04

COPY ./Stock_LSTM_Torch /Stock_LSTM_Torch
WORKDIR /Stock_LSTM_Torch

RUN apt update && apt install -y python3 python3-pip
RUN pip3 install --no-cache-dir -r requirements.txt


