spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/airflow"
  data:
    redis:
      host: localhost
      port: 6379
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-doc
